name: DevSecOps Unified Security Scan

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  # ---------------------------------------------------------------------------
  # 1. SAST - CodeQL (JavaScript / TypeScript)
  # ---------------------------------------------------------------------------
  sast-codeql:
    name: SAST (CodeQL Analysis)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recomendado para o TruffleHog analisar todo o histórico de commits

      # Validação de Segurança de Secrets (Secret Detection)
      - name: Scan para detecção de segredos (Secret Detection)
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: CodeQL Initialization
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ---------------------------------------------------------------------------
  # 2. SCA - OSV-Scanner (Multilinguagem)
  # ---------------------------------------------------------------------------
  sca-osv:
    name: SCA (OSV-Scanner)
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.5.1
